image: "ruby:2.6.5"

services:
  - postgres:12.2-alpine

variables:
  DB_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"
  - bundle exec rails db:create RAILS_ENV=test
  - bundle exec rails db:schema:load RAILS_ENV=test

stages:
  - security_check
  - code_style_check
  - tests

security check:
  stage: security_check
  script:
    - bundle exec brakeman

code style check:
  stage: code_style_check
  script:
    - bundle exec rubocop

tests:
  stage: tests
  script:
    - bundle exec rspec