# Common configuration.
AllCops:
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'config/*'
    - 'config/**/*'
    - 'app/admin/*'
    - 'lib/*'
    - '**/*_spec.rb'