---
openapi: 3.0.1
basePath: "/api/v1"
info:
  title: API V1
  version: v1
paths:
  "/confirmations/{id}":
    get:
      summary: anyone confirms the delivery of package
      tags:
      - packages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: package delivered
          content:
            application/json:
              schema:
                type: object
                properties:
                  tracking_number:
                    type: string
                  delivery_status:
                    type: string
                  estimated_delivery_date:
                    type: string
                    nullable: true
                  confirmation_token:
                    type: string
                  confirmation_expiration:
                    type: string
                required:
                - tracking_number
                - delivery_status
                - estimated_delivery_date
                - confirmation_token
                - confirmation_expiration
        '404':
          description: 'Error: package not found'
          content: {}
        '422':
          description: Validation failed
          content: {}
  "/auth/sign_in/":
    post:
      summary: courier sign_in
      tags:
      - couriers
      parameters: []
      responses:
        '200':
          description: courier logged in
          headers:
            access-token:
              type: string
              description: Access token
            client:
              type: string
              description: Client id
            expiry:
              type: string
              description: Token expiry date
            uid:
              type: string
              description: User email
          content: {}
        '401':
          description: courier not found
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
              - email
              - password
  "/couriers/{id}":
    put:
      summary: courier uploads lisence
      tags:
      - couriers
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: lisence successfully uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                    nullable: true
                  email:
                    type: string
                  avatar:
                    type: string
                required:
                - id
                - name
                - email
                - avatar
        '404':
          description: 'Error: unauthorized'
          content: {}
        '422':
          description: Second license upload unavailable
          content: {}
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: file
  "/packages/{id}":
    get:
      summary: courier retrieves a package
      tags:
      - packages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: package found
          content:
            application/json:
              schema:
                type: object
                properties:
                  tracking_number:
                    type: string
                  delivery_status:
                    type: string
                  estimated_delivery_date:
                    type: string
                    nullable: true
                required:
                - tracking_number
                - delivery_status
                - estimated_delivery_date
        '401':
          description: 'Error: unauthorized'
          content: {}
        '404':
          description: 'Error: package not found'
          content: {}
    put:
      summary: courier pick up a package
      tags:
      - packages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: package status successfully changed
          content:
            application/json:
              schema:
                type: object
                properties:
                  tracking_number:
                    type: string
                  delivery_status:
                    type: string
                  estimated_delivery_date:
                    type: string
                    nullable: true
                required:
                - tracking_number
                - delivery_status
                - estimated_delivery_date
        '401':
          description: 'Error: unauthorized'
          content: {}
        '404':
          description: 'Error: package not found'
          content: {}
    delete:
      summary: courier cancel a package
      tags:
      - packages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: package successfully deleted
          content: {}
        '401':
          description: 'Error: unauthorized'
          content: {}
        '404':
          description: 'Error: package not found'
          content: {}
  "/packages":
    get:
      summary: courier retrieves a list of Assigned packages
      tags:
      - packages
      parameters:
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: Assigned packages found
          content:
            application/json:
              schema:
                type: object
                properties:
                  packages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        estimated_delivery_date:
                          type: string
                          nullable: true
                        tracking_number:
                          type: string
                      required:
                      - id
                      - estimated_delivery_date
                      - tracking_number
        '401':
          description: 'Error: unauthorized'
          content: {}
  "/packages/{id}/generate_confirmation":
    get:
      summary: courier retrieves a package
      tags:
      - packages
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      - name: access-token
        in: header
        schema:
          type: string
      - name: token-type
        in: header
        schema:
          type: string
      - name: client
        in: header
        schema:
          type: string
      - name: expiry
        in: header
        schema:
          type: string
      - name: uid
        in: header
        schema:
          type: string
      responses:
        '200':
          description: package found
          content:
            application/json:
              schema:
                type: object
                properties:
                  confirmation_token:
                    type: string
                  confirmation_expiration:
                    type: string
                required:
                - confirmation_token
                - confirmation_expiration
        '401':
          description: 'Error: unauthorized'
          content: {}
        '404':
          description: 'Error: package not found'
          content: {}
        '422':
          description: 'Error: package not found'
          content: {}
servers:
- url: http://localhost:3000/api/v1
- url: https://intense-shore-07962.herokuapp.com/api/v1
