name: Delivery Service
on:
  push:
    pull_request:
      branches: [ develop ]
jobs:
  check_and_test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler --no-document
          bundle install --jobs 4 --retry 3
          yarn

      - name: Brakeman
        run: bundle exec brakeman

      - name: Rubocop checks
        run: bundle exec rubocop --fail-level E

      - name: Set up database
        run: |
          bundle exec rails db:create
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/db_test"

      - name: Test with RSpec
        env:
          RAILS_ENV: "test"
          DATABASE_URL: "postgres://postgres@localhost:5432/db_test"
        run: |
          bundle exec rspec
  deploy:
    needs: check_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_API}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true